fix(install): Bugs and optimization

diff --git a/bashbox b/bashbox
--- a/bashbox
+++ b/bashbox
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-main@bashbox%8089 () 
+main@bashbox%12799 () 
 { 
     \command \unalias -a;
     set -o pipefail;
@@ -25,7 +25,7 @@ main@bashbox%8089 ()
         esac
     };
     ___self="$0";
-    ___MAIN_FUNCNAME="main@bashbox%8089";
+    ___MAIN_FUNCNAME="main@bashbox%12799";
     NAME="bashbox";
     AUTHORS=("AXON <axonasif@gmail.com>");
     VERSION="0.1.5";
@@ -280,10 +280,6 @@ main@bashbox%8089 ()
         first_option="${1:0:1}";
         test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
     };
-    function okay::man () 
-    { 
-        echo hmmm
-    };
     function subcommand::new () 
     { 
         _positionals=();
@@ -493,17 +489,15 @@ EOF
                         continue
                     };
                 fi;
-                _repo_name="${_box%%::*}";
+                read -r -d '\n' _repo_name _tag_name < <(echo -e "${_box//::/\\n}") || true;
                 _repo_root_link="$(grep ".*/$_repo_name" "$_registry_meta_file")" || println::error "No such box as $_repo_name was found" 1;
-                _tag_name="${_box##*::}" && { 
-                    if [[ ! "$_tag_name" =~ ^[0-9]+\.[0-9]+ ]]; then
-                        { 
-                            _tag_name="$(curl --silent 					"${_github_api_root}/repos/${_repo_root_link##http*github.com\/}/tags" 						| head -n3 						| grep -m 1 -Po '"name": "\K.*?(?=")')"
-                        };
-                    fi
-                };
+                if [ -z "$_tag_name" ]; then
+                    { 
+                        _tag_name="$(curl --silent 					"${_github_api_root}/repos/${_repo_root_link##http*github.com\/}/tags" 						| head -n3 						| grep -m 1 -Po '"name": "\K.*?(?=")')" || println::error "Failed to fetch latest version tag of $_repo_name"
+                    };
+                fi;
                 _box_dir="$_bashbox_registrydir/${_repo_name}-${_tag_name}";
-                if test "$EXPORT_USEMOL" == "true"; then
+                if test "${EXPORT_USEMOL:-}" == "true"; then
                     { 
                         export "_usemol_${_repo_name}=${_box_dir}/src"
                     };
@@ -544,15 +538,16 @@ EOF
                 if test -e "$_box_dir/$_src_dir_name/main.sh"; then
                     { 
                         println::info "Compiling $_box in release mode";
-                        "$___self" build "$_box_dir" --release 2>&1 || { 
+                        subcommand::build --release "$_box_dir" 2>&1 || { 
                             println::error "Errors were found while compiling $_box, operation failed" 1
                         };
-                        _built_executable="$_box_dir/target/release/executable";
-                        _install_executable="$_bashbox_bindir/$_box";
+                        source "$_box_dir/$_bashbox_meta_name";
+                        _built_executable="$_box_dir/target/release/$NAME";
+                        _install_executable="$_bashbox_bindir/$NAME";
                         chmod +x "$_built_executable";
                         ln -srf "$_built_executable" "$_install_executable";
                         chmod +x "$_install_executable";
-                        println::info "$_box was successfully installed"
+                        println::info "$_box was successfully installed as $NAME"
                     };
                 else
                     { 
@@ -1633,4 +1628,4 @@ For bugreports: $REPOSITORY"
     };
     main "$@"
 }
-main@bashbox%8089 "$@"
+main@bashbox%12799 "$@"
