refactor: Bootstrap println::error() into the executable

diff --git a/bashbox b/bashbox
--- a/bashbox
+++ b/bashbox
@@ -1,6 +1,22 @@
 #!/usr/bin/env bash
-main@bashbox%7928 () 
+main@bashbox%18343 () 
 { 
+    function println::error () 
+    { 
+        local _return_code=${2:-$?};
+        local _source="${BB_ERR_SOURCE:-"${BASH_SOURCE[0]}"}";
+        local _command="$1";
+        test "${_PRINT_HELP:-no}" == yes && print_help 1>&2;
+        echo -e "[!!!] ${BRED}ERROR${RC}[$_return_code]: $_source[$BASH_LINENO]: $_command";
+        case "${JOB:-"exit"}" in 
+            exit)
+                exit $_return_code
+            ;;
+            kill)
+                kill -9 "$BASHPID"
+            ;;
+        esac
+    };
     set -o pipefail;
     set -o errexit;
     set -o errtrace;
@@ -210,7 +226,14 @@ main@bashbox%7928 ()
         local _command="$1";
         test "${_PRINT_HELP:-no}" == yes && print_help 1>&2;
         echo -e "[!!!] ${BRED}ERROR${RC}[$_return_code]: $_source[$BASH_LINENO]: $_command";
-        exit $_return_code
+        case "${JOB:-"exit"}" in 
+            exit)
+                exit $_return_code
+            ;;
+            kill)
+                kill -9 "$BASHPID"
+            ;;
+        esac
     };
     readonly RC='\033[0m' RED='\033[0;31m' BRED='\033[1;31m' GRAY='\033[1;30m';
     readonly BLUE='\033[0;34m' BBLUE='\033[1;34m' CYAN='\033[0;34m' BCYAN='\033[1;34m';
@@ -445,7 +468,7 @@ main@bashbox%7928 ()
                     ( cd "$_src";
                     if test ! -e "${_parsed_input}.sh" && test ! -e "${_parsed_input}"; then
                         { 
-                            ( kill -9 "$0" ) & println::error "$_input is missing" 1
+                            println::error "$_input is missing" 1
                         };
                     fi;
                     if grep '\*;$' <<< "$(awk '{$1=$1;print}' <<<"$_input")" > /dev/null; then
@@ -504,6 +527,7 @@ main@bashbox%7928 ()
         local _ran="$RANDOM";
         local _tmp_bbb_path="$_target_workdir/.bb_bootstrap.$_ran";
         echo '#!'"$(command -v env) bash" > "$_tmp_bbb_path";
+        declare -f 'println::error' >> "$_tmp_bbb_path";
         echo "${_bb_bootstrap}" >> "$_tmp_bbb_path";
         cat "$_bashbox_meta" >> "$_tmp_bbb_path";
         cat "$_tmp_bbb_path" "$_target_workdir/main.sh" > "$_target_workfile";
@@ -878,6 +902,7 @@ EOF
 	_used_symbols_statfile="$_main_src_dir/.used_symbols";
 EOF
 
+        declare -f 'println::error' >> "$_target_workfile";
         declare -f __use_func >> "$_target_workfile";
         cat "$_target_workdir/main.sh" >> "$_target_workfile";
         geco "\nmain \"\$@\";" >> "$_target_workfile";
@@ -1070,4 +1095,4 @@ For bugreports: https://github.com/gearlock-users-repo/issues"
     main "$@"
 }
 
-main@bashbox%7928 "$@";
+main@bashbox%18343 "$@";
