fix:(bootstrap-header): Unexpected behaviors on UNCAUGHT EXCEPTIONS

diff --git a/bashbox b/bashbox
--- a/bashbox
+++ b/bashbox
@@ -1,24 +1,25 @@
 #!/usr/bin/env bash
-main@bashbox%9836 () 
+main@bashbox%7973 () 
 { 
+    function process::self::exit () 
+    { 
+        kill -USR1 "$___self_PID"
+    };
     function log::error () 
     { 
-        local _lasttoken="$_";
-        local _exception_line="${1}";
-        local _retcode="${2}";
-        local IFS=' 	
-';
+        local _retcode="${2:-$?}";
+        local _exception_line="$1";
         local _source="${BB_ERR_SOURCE:-"${BASH_SOURCE[-1]}"}";
-        echo -e "[!!!] \033[1;31merror\033[0m[$_retcode]: ${_source##*/}[$BASH_LINENO]: ${STACK_TRACE:-"$_exception_line"}" 1>&2;
-        if test -v STACK_TRACE; then
+        echo -e "[!!!] \033[1;31merror\033[0m[$_retcode]: ${_source}[$BASH_LINENO]: ${BB_ERR_MSG:-"$_exception_line"}" 1>&2;
+        if test -v BB_ERR_MSG; then
             { 
-                echo -e "STACK TRACE: (TOKEN: $_lasttoken) $_exception_line";
+                echo -e "STACK TRACE: (TOKEN: $_exception_line)" 1>&2;
                 local -i _frame=0;
                 local _treestack='|--';
                 local _line _caller _source;
                 while read -r _line _caller _source < <(caller "$_frame"); do
                     { 
-                        echo "$_treestack ${_caller} >> ${_source##*/}::${_line}";
+                        echo "$_treestack ${_caller} >> ${_source##*/}::${_line}" 1>&2;
                         _frame+=1;
                         _treestack+='--'
                     };
@@ -27,41 +28,42 @@ main@bashbox%9836 ()
         fi;
         return "$_retcode"
     };
-    \command \trap 'exit' USR1;
-    \command \trap 'STACK_TRACE="UNCAUGHT EXCEPTION" log::error "$BASH_COMMAND" $? || { kill -USR1 "$___self_PID"; }' ERR;
-    \command \unalias -a;
+    \command \unalias -a || exit;
+    trap 'exit' USR1;
+    trap 'BB_ERR_MSG="UNCAUGHT EXCEPTION" log::error "$BASH_COMMAND" || process::self::exit' ERR;
     set -eEuT -o pipefail;
     shopt -s inherit_errexit expand_aliases;
     ___self="$0";
     ___self_PID="$$";
-    ___MAIN_FUNCNAME="main@bashbox%9836";
+    ___MAIN_FUNCNAME="main@bashbox%7973";
     ___self_NAME="BashBox";
     ___self_CODENAME="bashbox";
     ___self_AUTHORS=("AXON <axonasif@gmail.com>");
-    ___self_VERSION="0.2.8";
+    ___self_VERSION="0.2.9";
     ___self_DEPENDENCIES=("std::0.1.5" "argbash::0.1.0");
     ___self_REPOSITORY="https://github.com/axonasif/bashbox";
-    ___self_BASHBOX_COMPAT="0.2.8~";
+    ___self_BASHBOX_COMPAT="0.2.9~";
     function bb_bootstrap_header () 
     { 
+        function process::self::exit () 
+        { 
+            kill -USR1 "$___self_PID"
+        };
         function log::error () 
         { 
-            local _lasttoken="$_";
-            local _exception_line="${1}";
-            local _retcode="${2}";
-            local IFS=' 	
-';
+            local _retcode="${2:-$?}";
+            local _exception_line="$1";
             local _source="${BB_ERR_SOURCE:-"${BASH_SOURCE[-1]}"}";
-            echo -e "[!!!] \033[1;31merror\033[0m[$_retcode]: ${_source##*/}[$BASH_LINENO]: ${STACK_TRACE:-"$_exception_line"}" 1>&2;
-            if test -v STACK_TRACE; then
+            echo -e "[!!!] \033[1;31merror\033[0m[$_retcode]: ${_source}[$BASH_LINENO]: ${BB_ERR_MSG:-"$_exception_line"}" 1>&2;
+            if test -v BB_ERR_MSG; then
                 { 
-                    echo -e "STACK TRACE: (TOKEN: $_lasttoken) $_exception_line";
+                    echo -e "STACK TRACE: (TOKEN: $_exception_line)" 1>&2;
                     local -i _frame=0;
                     local _treestack='|--';
                     local _line _caller _source;
                     while read -r _line _caller _source < <(caller "$_frame"); do
                         { 
-                            echo "$_treestack ${_caller} >> ${_source##*/}::${_line}";
+                            echo "$_treestack ${_caller} >> ${_source##*/}::${_line}" 1>&2;
                             _frame+=1;
                             _treestack+='--'
                         };
@@ -70,9 +72,9 @@ main@bashbox%9836 ()
             fi;
             return "$_retcode"
         };
-        \command \trap 'exit' USR1;
-        \command \trap 'STACK_TRACE="UNCAUGHT EXCEPTION" log::error "$BASH_COMMAND" $? || { kill -USR1 "$___self_PID"; }' ERR;
-        \command \unalias -a;
+        \command \unalias -a || exit;
+        trap 'exit' USR1;
+        trap 'BB_ERR_MSG="UNCAUGHT EXCEPTION" log::error "$BASH_COMMAND" || process::self::exit' ERR;
         set -eEuT -o pipefail;
         shopt -s inherit_errexit expand_aliases
     };
@@ -530,7 +532,7 @@ EOF
                     _box_dir="$_repo_source";
                     if test ! -e "$_box_dir"; then
                         { 
-                            log::error "$_box_dir does not exist" 1 || exit
+                            log::error "$_box_dir does not exist" 1 || process::self::exit
                         };
                     fi;
                     _arg_force=off;
@@ -552,7 +554,7 @@ EOF
                 else
                     if string::matches "$_repo_source" "[a-zA-Z0-9_]"; then
                         { 
-                            _repo_url="$(grep ".*/${_repo_source}$" "$_registry_meta_file")" || log::error "No such box as $_repo_source was found in the registry" 1 || exit;
+                            _repo_url="$(grep ".*/${_repo_source}$" "$_registry_meta_file")" || log::error "No such box as $_repo_source was found in the registry" 1 || process::self::exit;
                             _box_dir="$_bashbox_registrydir/${_repo_source}-${_tag_name}";
                             _box_name="${_repo_source##*/}"
                         };
@@ -617,7 +619,7 @@ EOF
                     { 
                         log::info "Compiling $_box in release mode";
                         ( subcommand::build --release "$_box_dir" 2>&1 ) || { 
-                            log::error "Errors were found while compiling $_box, operation failed" 1 || exit
+                            log::error "Errors were found while compiling $_box, operation failed" 1 || process::self::exit
                         };
                         source "$_box_dir/$_bashbox_meta_name";
                         _built_executable="$_box_dir/target/release/$CODENAME";
@@ -944,7 +946,7 @@ ${YELLOW}${_self_name} ${_subcommand_argv} --release --release -- arg1 arg2 \"st
                     fi;
                     if test ! -e "${_parsed_input}.sh" && test ! -e "${_parsed_input}"; then
                         { 
-                            log::error "$_input is missing" 1 || exit
+                            log::error "$_input is missing" 1 || process::self::exit
                         };
                     fi;
                     if grep '\*;$' <<< "$(awk '{$1=$1;print}' <<<"$_input")" > /dev/null; then
@@ -1550,6 +1552,7 @@ EOF
         done;
         log::info "Installing to $_target_install_dir";
         local _target_full_path="$_target_install_dir/$___self_CODENAME";
+        rm -f "$_target_full_path";
         echo '#!/usr/bin/env bash' > "$_target_full_path";
         declare -f "${___MAIN_FUNCNAME}" >> "$_target_full_path";
         echo "${___MAIN_FUNCNAME} \"\$@\";" >> "$_target_full_path";
@@ -1558,6 +1561,8 @@ EOF
     };
     function subcommand::clean () 
     { 
+        read -r bruh < <(false);
+        read;
         function print_help () 
         { 
             println::helpgen ${_self_name^^}-${_subcommand_argv^^} --short-desc "${SUBCOMMANDS_DESC[4]}" --usage "${_self_name} $_subcommand_argv <path>" --examples "### The basic way:
@@ -1849,4 +1854,4 @@ For bugreports: $___self_REPOSITORY"
     };
     main "$@"
 }
-main@bashbox%9836 "$@";
+main@bashbox%7973 "$@";
